name: Prachi site CI

on:
  push:
    branches: [ "prachi" ]
  pull_request:
    branches: [ "prachi" ]

jobs:
  prachi-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the site in the jekyll/builder container for Prachi
        run: |
          docker run \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
